using PragmaticScaffolder.Core.Models;
using PragmaticScaffolder.Core.Services.Generators;

namespace PragmaticScaffolder.Core.Services;

/// <summary>
/// Orchestrates all generators and optionally writes files to disk.
/// Each generator is independent — add new ones here without touching existing code.
/// </summary>
public sealed class GenerationEngine
{
    private static readonly IReadOnlyList<Func<GenerationRequest, IEnumerable<GeneratedFile>>> Generators =
    [
        r => new EntityGenerator().Generate(r),
        r => new DbContextGenerator().Generate(r),
        r => new DtoGenerator().Generate(r),
        r => new ServiceGenerator().Generate(r),
        r => new EndpointsGenerator().Generate(r),
        r => new BlazorApiClientGenerator().Generate(r),
        r => new BlazorPageGenerator().Generate(r),
        r => new TestsGenerator().Generate(r),
        r => new ProjectFilesGenerator().Generate(r),
    ];

    /// <summary>Returns generated files without writing to disk — useful for preview.</summary>
    public GenerationResult Preview(GenerationRequest request)
        => Run(request, writeToDisk: false);

    /// <summary>Generates all files and writes them to <see cref="GenerationRequest.OutputPath"/>.</summary>
    public GenerationResult Generate(GenerationRequest request)
        => Run(request, writeToDisk: true);

    private static GenerationResult Run(GenerationRequest request, bool writeToDisk)
    {
        var result = new GenerationResult { Success = true };

        foreach (var generator in Generators)
        {
            try
            {
                result.Files.AddRange(generator(request));
            }
            catch (Exception ex)
            {
                result.Errors.Add(ex.Message);
                result.Success = false;
            }
        }

        if (writeToDisk && result.Success)
        {
            WriteToDisk(request.OutputPath, result.Files, result.Errors);
            result.WrittenToDisk = result.Errors.Count == 0;
            if (result.Errors.Count > 0) result.Success = false;
        }

        return result;
    }

    private static void WriteToDisk(string outputPath, List<GeneratedFile> files, List<string> errors)
    {
        foreach (var file in files)
        {
            try
            {
                var fullPath = Path.Combine(outputPath, file.RelativePath.Replace('/', Path.DirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);

                // Skip files the developer has customised (no auto-generated header)
                if (File.Exists(fullPath))
                {
                    var firstLine = File.ReadLines(fullPath).FirstOrDefault() ?? string.Empty;
                    if (!firstLine.Contains("<auto-generated />"))
                        continue;
                }

                File.WriteAllText(fullPath, file.Content);
            }
            catch (Exception ex)
            {
                errors.Add($"Failed writing '{file.RelativePath}': {ex.Message}");
            }
        }
    }
}
